'use client'
import { FormEvent,useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'
import { Eye,EyeOff,LockKeyhole,Mail,Moon,ShieldCheck,Sun } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
export default function LoginPage(){
 const router=useRouter(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [show,setShow]=useState(false); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [dark,setDark]=useState(true)
 useEffect(()=>{const s=localStorage.getItem('theme');const d=s?s==='dark':true;setDark(d);document.documentElement.dataset.theme=d?'dark':'light'},[])
 function toggle(){const d=!dark;setDark(d);document.documentElement.dataset.theme=d?'dark':'light';localStorage.setItem('theme',d?'dark':'light')}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setLoading(true);try{const s=createClient();const {error}=await s.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error){setError(error.message==='Invalid login credentials'?'E-mail ou senha incorretos.':error.message);return}router.replace('/dashboard');router.refresh()}catch(err){setError(err instanceof Error?err.message:'Não foi possível entrar.')}finally{setLoading(false)}}
 return <main className="login-shell"><button className="theme-toggle" onClick={toggle} type="button">{dark?<Sun size={19}/>:<Moon size={19}/>}</button><section className="brand-panel"><div className="brand"><div className="logo">O</div><div><strong>Opera360</strong><span>Gestão operacional</span></div></div><div className="brand-copy"><span className="eyebrow">CONTROLE DE VERDADE</span><h1>Organize a equipe.<br/>Controle os custos.<br/><em>Veja o lucro.</em></h1><p>Eventos, trabalhadores, presença, transporte, alimentação, pagamentos e resultados em um único sistema.</p></div><div className="safe"><ShieldCheck/><div><strong>Acesso restrito</strong><span>Somente usuários autorizados.</span></div></div></section><section className="form-panel"><form className="login-card" onSubmit={submit}><span className="eyebrow">PAINEL DA EQUIPE</span><h2>Bem-vindo.</h2><p className="sub">Entre com seu e-mail e senha.</p><label><span>E-mail</span><div className="field"><Mail size={18}/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="seu@email.com" required/></div></label><label><span>Senha</span><div className="field"><LockKeyhole size={18}/><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Sua senha" required/><button type="button" className="icon" onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{error&&<div className="error">{error}</div>}<button className="login-btn" disabled={loading}>{loading?'Entrando...':'Entrar no painel'}</button><div className="foot"><ShieldCheck size={15}/>Sessão protegida pelo Supabase Auth.</div></form></section></main>
}
